### ISSUE TITLE
exoticaz配置文件报错: exoticaz种子信息解析使用了错误的CSS选择器

### ISSUE THREAD

**Issue by Eyeseas** [htnanako/movie-robot-public#10]
MR版本：1.9.75

出现情况：
搜索报错，以及自动更新种子信息时报错，都是下面相同的错

报错信息：
```
2023/04/17 23:44:24 - ThreadPoolExecutor-5_3 - INFO: 开始同步站点资源信息...
 2023/04/17 23:44:27 - ThreadPoolExecutor-5_3 - INFO: exoticaz获取最新种子列表失败，自动重试中，错误信息：SiteParseException("exoticaz种子信息解析使用了错误的CSS选择器：Expected an argument, got <S ' ' at 84>")
 2023/04/17 23:44:48 - ThreadPoolExecutor-5_3 - INFO: exoticaz获取最新种子列表失败，自动重试中，错误信息：SiteParseException("exoticaz种子信息解析使用了错误的CSS选择器：Expected an argument, got <S ' ' at 84>")
 2023/04/17 23:45:10 - ThreadPoolExecutor-5_3 - INFO: exoticaz获取最新种子列表失败，自动重试中，错误信息：SiteParseException("exoticaz种子信息解析使用了错误的CSS选择器：Expected an argument, got <S ' ' at 84>")
 2023/04/17 23:45:31 - ThreadPoolExecutor-5_3 - INFO: exoticaz获取最新种子列表失败，自动重试中，错误信息：SiteParseException("exoticaz种子信息解析使用了错误的CSS选择器：Expected an argument, got <S ' ' at 84>")
 2023/04/17 23:45:53 - ThreadPoolExecutor-5_3 - INFO: exoticaz获取最新种子列表失败，自动重试中，错误信息：SiteParseException("exoticaz种子信息解析使用了错误的CSS选择器：Expected an argument, got <S ' ' at 84>")
```

相关请求：
<img width="940" alt="image" src="https://user-images.githubusercontent.com/18658548/232543476-4fc217d3-90bc-44ec-8a5f-89b3a0d6c41e.png">

请求返回正常(只了配置文件中的selector的部分)：
```html
        <div class="card mt-2">
            <h1 class="card-header h4">Torrents</h1>
            <div class="card-body p-2">
                <div class="float-right mb-1"></div>
                <span class="badge badge-secondary">1 torrent</span>
                <span class="badge badge-light">Keyword: mudr 201</span>
                <div class="table-responsive">
                    <table class="table table-sm table-bordered table-hover">
                        <thead class="bg-body">
                            <tr>
                                <th style="width: 32px;">&nbsp;</th>
                                <th>
                                    <span>File</span>
                                    <div class="float-right">
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&order=thanks&sort=desc"
                                            class="sort" data-toggle="tooltip" title="Order by Thanks">Th<i
                                                class="fa fa-fw fa-sort"></i></a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&order=comments&sort=desc"
                                            class="sort" data-toggle="tooltip" title="Order by Comments">Co<i
                                                class="fa fa-fw fa-sort"></i></a>
                                        <span class="user-group">Uploader</span>
                                    </div>
                                </th>
                                <th>&nbsp;</th>
                                <th style="width: 100px;"><a
                                        href="https://exoticaz.to/torrents?search=mudr+201&order=age&sort=asc"
                                        class="sort" data-toggle="tooltip" title="Order by Age">Age<i
                                            class="fa fa-fw fa-sort-down"
                                            title="Descending Order (big to small)"></i></a></th>
                                <th style="width: 95px;"><a
                                        href="https://exoticaz.to/torrents?search=mudr+201&order=size&sort=desc"
                                        class="sort" data-toggle="tooltip" title="Order by Size">Size<i
                                            class="fa fa-fw fa-sort"></i></a></th>
                                <th><a href="https://exoticaz.to/torrents?search=mudr+201&order=seed&sort=desc"
                                        class="sort" data-toggle="tooltip" title="Order by Seeds">S<i
                                            class="fa fa-fw fa-sort"></i></a></th>
                                <th><a href="https://exoticaz.to/torrents?search=mudr+201&order=leech&sort=desc"
                                        class="sort" data-toggle="tooltip" title="Order by Leeches">L<i
                                            class="fa fa-fw fa-sort"></i></a></th>
                                <th><a href="https://exoticaz.to/torrents?search=mudr+201&order=complete&sort=desc"
                                        class="sort" data-toggle="tooltip" title="Order by Completed">C<i
                                            class="fa fa-fw fa-sort"></i></a></th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="">
                                <td>
                                    <i class="fa fa-video category-icon" title="Video Clip" data-toggle="tooltip"></i>
                                </td>
                                <td>
                                    <div class="screen-image d-inline-block float-left mr-1" data-id="72062"
                                        data-screens="https://i.exoticaz.to/images/torrent/8/2/e/nsyntdq0u5ik.th.jpg|https://i.exoticaz.to/images/torrent/6/c/7/srhtdou9fa8r.th.jpg|https://i.exoticaz.to/images/torrent/0/0/4/jjtouum9xcin.th.jpg|https://i.exoticaz.to/images/torrent/a/8/f/xfmngothlzx5.th.jpg|https://i.exoticaz.to/images/torrent/e/5/c/tbh50uy3cyaw.th.jpg|https://i.exoticaz.to/images/torrent/3/0/0/czdajpjdmatu.th.jpg">
                                        <img src="https://i.exoticaz.to/images/torrent/8/2/e/nsyntdq0u5ik.th.jpg"
                                            alt="[MUDR-201] A gal who loves her uncle too much If she asks for it, she&#039;ll forgive everything, whether it&#039;s cum swallowing or vaginal cum shot! Lima Arai"
                                            style="width: 64px; height: auto;">
                                    </div>
                                    <div class="mb-1">
                                        <span data-toggle="tooltip" title="Asian"><i
                                                class="fa fa-yin-yang text-dark"></i></span>
                                        <a href="https://exoticaz.to/torrent/72062"
                                            title="[MUDR-201] A gal who loves her uncle too much If she asks for it, she&#039;ll forgive everything, whether it&#039;s cum swallowing or vaginal cum shot! Lima Arai"
                                            class="torrent-link">
                                            [MUDR-201] A gal who loves her uncle too much If she asks for it,
                                            she&#039;ll forgive everyth...
                                        </a>
                                        <span data-toggle="tooltip" title="Censored"><i
                                                class="fa fa-ban text-warning"></i></span>
                                    </div>
                                    <div class="d-inline-block float-right">
                                        <a href="https://exoticaz.to/profile/exoticbot"
                                            class="m-0 user-group group-uploader" title="exoticbot">
                                            exoticbot
                                            <span class="tag-addon text-pink"><i class="fa fa-robot"
                                                    title="Uploaded by a Bot"></i></span>
                                        </a>
                                    </div>
                                    <div class="tags">
                                        <div class="tag tag-gray">1080p
                                            <span class="tag-addon tag-dark text-teal px-1">HD</span>
                                        </div>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;performers%5B0%5D=6191"
                                            class="tag tag-dark" title="Rima ARAI" data-toggle="popover"
                                            data-placement="auto"
                                            data-content='<img src="https://i.exoticaz.to/images/performer/8/e/5/ctkpi58sotpl.th.jpg" width="140" height="160" class="img-fluid">'
                                            data-html="true" data-trigger="hover">Rima ARAI</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;studios%5B0%5D=206"
                                            title="Search for MUKU" class="tag tag-gray">MUKU</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;tags%5B0%5D=41"
                                            title="Search for big.tits" class="tag">big.tits</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;tags%5B0%5D=100"
                                            title="Search for creampie" class="tag">creampie</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;tags%5B0%5D=1965"
                                            title="Search for gyaru" class="tag">gyaru</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;tags%5B0%5D=2"
                                            title="Search for japanese" class="tag">japanese</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;tags%5B0%5D=1286"
                                            title="Search for live.action" class="tag">live.action</a>
                                        <a href="https://exoticaz.to/torrents?search=mudr+201&amp;tags%5B0%5D=90"
                                            title="Search for uniform" class="tag">uniform</a>
                                    </div>
                                </td>
                                <td>
                                    <div class="align-top">
                                        <a href="https://exoticaz.to/download/torrent/xxxx.xxxxxxxxxxxxxx.torrent"
                                            title="Download this Torrent" class="sort">
                                            <i class="fa fa-download"></i></a>
                                    </div>
                                    <div class="align-bottom">
                                        <a href="#" data-toggle="tooltip" title="Bookmark this Torrent"
                                            class="sort button-ajax-action"
                                            data-url="https://exoticaz.to/bookmark/72062" data-content="Torrent"
                                            data-action="Bookmark"><i class="fa fa-bookmark"></i>
                                        </a>
                                    </div>
                                </td>
                                <td>7 months</td>
                                <td>6.22 GB</td>
                                <td>6</td>
                                <td>0</td>
                                <td>58</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <table class="table table-sm table-bordered table-striped">
                    <tbody>
                        <tr class="table-danger">
                            <td>Recently Downloaded, Inactive Torrents</td>
                        </tr>
                        <tr class="table-warning">
                            <td>Downloaded Torrents</td>
                        </tr>
                        <tr class="table-success">
                            <td>Active Torrents</td>
                        </tr>
                        <tr class="table-info">
                            <td>Download Incomplete</td>
                        </tr>
                        <tr>
                            <td class="bg-light">
                                <div class="d-inline mr-3"><i class="fa fa-times-circle text-red"></i> Unverified
                                    Torrent</div>
                                <div class="d-inline mr-3"><i class="fa fa-star text-yellow"></i> Free Download Torrent
                                </div>
                                <div class="d-inline mr-3"><i class="fa fa-star-half-alt text-pink"></i> Half Download
                                    Torrent
                                </div>
                                <div class="d-inline mr-3"><i class="fa fa-gem text-green"></i> Double Upload Torrent
                                </div>
                            </td>
                        </tr>
                    </tbody>
                </table>
                <div class="float-right"></div>
            </div>
            <div class="card-footer text-muted"></div>
        </div>

```

**Comment by Eyeseas** [comment]
搜索的报错
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/18658548/232547192-0b555373-8852-4479-9659-4625e144e410.png">

**Comment by htnanako** [comment]
把你本地的exo配置文件贴上来。

**Comment by Eyeseas** [comment]
> 把你本地的exo配置文件贴上来。

```yaml
#!DATA etag=9c9006c4b1ef5e97958d7cc4bc6dc6acf092770895197b0057586dd056b826d8
id: exoticaz
name: exoticaz
domain: https://exoticaz.to/
encoding: UTF-8
config_url: https://ghproxy.com/https://raw.githubusercontent.com/htnanako/movie-robot-public/main/app/sites/exoticaz.yml

login:
  test:
    selector: a[href="https://exoticaz.to/messenger"]

category_mappings:
  - { id: "Video Clip", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "Video Clip" }
  - { id: "Video Pack", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "Video Pack" }
  - { id: "Siterip Pack", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "Siterip Pack" }
  - { id: "Pornstar Pack", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "Pornstar Pack" }
  - { id: "DVD", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "DVD" }
  - { id: "BluRay", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "BluRay" }
  - { id: "Photo Pack", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "Photo Pack" }
  - { id: "Books & Magazines", cate_level1: AV, cate_level2: "XXX" , cate_level2_desc: "Books & Magazines" }

userinfo:
  path: https://exoticaz.to/support
  item:
    selector: div.ratio-bar
  fields:
    uid:
      text: 0
    user_group:
      text: 'user'
    username:
      default_value: '未知用户名'
      selector: div > div:nth-child(1) > a > span
    uploaded:
      default_value: 0
      selector: div > div:nth-child(3)
      content: -1
    downloaded:
      default_value: 0
      selector: div > div:nth-child(4)
      content: -1
    seeding:
      default_value: 0
      selector: div > div:nth-child(7)
      contents: -1
    leeching:
      default_value: 0
      selector: div > div:nth-child(8)
      content: -1
    vip_group:
      case:
        a[class^="VIP"]: true
        "*": false
search:
  paths:
    - path: torrents
      method: get
  query:
    $raw: "{% for c in query.cates %}category[]={{c}}{% endfor %}"
    search: "{{ query.keyword }}"
    order: "{{ query.sort }}"
    page: "{{ query.page }}"

torrents:
  list:
    selector: div.card.mt-2 > div.card-body.p-2 > div.table-responsive > table > tbody > tr:has(i)
  fields:
    id:
      selector: a[href^="https://exoticaz.to/torrent/"]
      attribute: href
      filters:
        - name: re_search
          args: [ '\d+', 0 ]
    title:
      selector: a[href^="https://exoticaz.to/torrent/"]
    category:
      selector: td:nth-child(1) > i.fa.fa-video.category-icon[title]
      attribute: title
    details:
      selector: a[href^="https://exoticaz.to/torrent/"]
      attribute: href
      filters:
        - name: replace
          args: ["https://exoticaz.to/", ""]
    download:
      selector: a[href^="https://exoticaz.to/download/torrent/"]
      attribute: href
    poster:
      selector: td:nth-child(2) > div.screen-image.d-inline-block.float-left.mr-1 > img
      attribute: src
    date:
      selector: td:nth-child(4)
      filters:
        - name: date_en_elapsed_parse
    size:
      selector: td:nth-child(5)
    seeders:
      selector: td:nth-child(6)
    leechers:
      selector: td:nth-child(7)
    grabs:
      selector: td:nth-child(8)
    downloadvolumefactor:
      case:
        i.fa.fa-star.text-yellow: 0
        i.fa.fa-star-half-alt.text-pink: 0.5
        "*": 1
    uploadvolumefactor:
      case:
        i.fa.fa-gem.text-green: 2
        "*": 1
    free_deadline:
      default_value: "{% if fields['downloadvolumefactor']==0 %}{{max_time}}{% endif%}"
      default_value_format: '%Y-%m-%d %H:%M:%S.%f'
    minimumratio:
      text: 1
    minimumseedtime:
      text: 2073600
```
